server:
    port: 1200

    servlet:
        context-path: /tasty-town

spring:
    datasource:
        url: jdbc:mysql://localhost/tasty-town
        username: root
        password: root

    jpa:
        hibernate:
            ddl_auto: update

        show-sql: true

    # File Upload Configuration
    #multipart:
        #location: D:/tasty_town_uploads
upload:
    file:
        dir: foodImage


 